My Dev/force-app/main/default/objects/Record_DML_Event__e/Record_DML_Event__e.object-meta.xml
<CustomObject>
    <description>A generic PE to perform Async Record DML on any of the provided object</description>
    <label>Record DML Event</label>
    <pluralLabel>Record DML Events</pluralLabel>
</CustomObject>

My Dev/force-app/main/default/objects/Record_DML_Event__e/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>Type of DML Operation(INSERT, UPDATE, UPSERT, DELETE</description>
    <label>Operation</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

My Dev/force-app/main/default/objects/Record_DML_Event__e/fields/Record_JSON__c.field-meta.xml
<CustomField>
    <fullName>Record_JSON__c</fullName>
    <label>Record JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

My Dev/force-app/main/default/classes/RecordDMLEventTriggerHandler.cls
/*
* Name              : RecordDMLEventTriggerHandler
* Description       : Handler class for  Record_DML_Event__e trigger
* Created           : 4th March 2026
* ------------------------- Change History -----------------------------
* Change Type       : Created
* Change Date       : 4th March 2026
* Change Description: Created
*/
public with sharing class RecordDMLEventTriggerHandler {

    /*
    * @methodName      : handleAfterInsert
    * @description     : This method is used to handle the after insert event
    * @param           : List<Record_DML_Event__e>
    * @return          : void
    * @exception       : none
    * @changeHistory   : none
    */
    public static void handleAfterInsert(List<Record_DML_Event__e> newEventList) {
        Map<String, List<sObject>> operationToEventMap = new Map<String, List<sObject>>();
        for (Record_DML_Event__e recordDMLEvent : newEventList) {
            if(!operationToEventMap.containsKey(recordDMLEvent.Operation__c)) {
                operationToEventMap.put(recordDMLEvent.Operation__c, new List<sObject>());
            }
            operationToEventMap.get(recordDMLEvent.Operation__c).addAll((List<sObject>)JSON.deserialize(recordDMLEvent.Record_JSON__c, List<sObject>.class));
        }
        
        if(operationToEventMap.size() > 0) {
            RecordDMLService.processDML(operationToEventMap);
        }
    }
}